const page=document.body.dataset.page||"";
const infoPages=["faq.html","contact.html","return-policy.html","shipping-policy.html","terms.html","privacy-policy.html"];
const currentFile=location.pathname.split("/").pop()||"index.html";
if(infoPages.includes(currentFile))document.body.classList.add("info-page");
const svg=paths=>`<svg aria-hidden="true" viewBox="0 0 24 24">${paths}</svg>`;
const instagram="https://www.instagram.com/reel/DZ5JCxYhJnP/?igsh=MWVndHQ2cnljNnJ5bA==";
document.body.insertAdjacentHTML("afterbegin",`<div class="topbar"><div class="marquee"><div class="marquee__track"><div class="marquee__group"><span>♡ Free shipping above ₹499</span><i>|</i><span>▣ COD available</span><i>|</i><span>↩ Easy 7-day exchange or return</span><i>|</i></div><div class="marquee__group"><span>♡ Free shipping above ₹499</span><i>|</i><span>▣ COD available</span><i>|</i><span>↩ Easy 7-day exchange or return</span><i>|</i></div><div class="marquee__group"><span>♡ Free shipping above ₹499</span><i>|</i><span>▣ COD available</span><i>|</i><span>↩ Easy 7-day exchange or return</span><i>|</i></div></div></div></div><header class="site-header"><div class="header__inner"><button class="mobile-menu" type="button" aria-label="Open menu" aria-expanded="false">${svg('<path d="M4 7h16M4 12h16M4 17h16"/>')}</button><a class="brand" href="index.html"><img src="Assets/giraalogo.png" alt="Giraastore"></a><nav class="main-nav"><a href="index.html">Home</a><a class="${page==='shop'?'active':''}" href="shop.html">Shop</a><a href="shop.html">New Arrivals</a><a href="shop.html">Best Sellers</a><a href="shop.html">Collections</a><a href="about.html">About Us</a><a class="${page==='contact'?'active':''}" href="contact.html">Contact Us</a></nav><div class="header-actions"><a href="shop.html" aria-label="Search">${svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>')}</a><a href="contact.html" aria-label="My account">${svg('<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>')}</a><a href="wishlist.html" aria-label="Wishlist">${svg('<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/>')}</a><button class="cart-action" aria-label="Shopping cart">${svg('<path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>')}<span class="cart-count">0</span></button></div></div></header>`);
const nav=document.querySelector('.main-nav');
const shopLink=[...nav.children].find(el=>el.matches('a')&&el.textContent.trim()==='Shop');
const collectionLink=[...nav.children].find(el=>el.matches('a')&&el.textContent.trim()==='Collections');
shopLink.outerHTML=`<div class="nav-item has-dropdown shop-nav"><button class="nav-trigger" type="button" aria-expanded="false">Shop ${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="dropdown-panel shop-menu"><div class="mega-heading">Shop</div><div class="submenu-item"><button class="submenu-trigger" type="button" aria-expanded="false"><span>✨ Featured</span>${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="submenu-panel"><a href="shop.html">New Arrivals</a><a href="shop.html">Best Sellers</a><a href="shop.html">Sale</a><a href="shop.html">All Products</a></div></div><div class="submenu-item"><button class="submenu-trigger" type="button" aria-expanded="false"><span>📝 Stationery</span>${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="submenu-panel"><a href="shop.html">Notebooks</a><a href="shop.html">Pens</a><a href="shop.html">Stickers</a><a href="shop.html">Washi Tape</a><a href="shop.html">Pencil Cases</a><a href="shop.html">Highlighters</a></div></div><div class="submenu-item"><button class="submenu-trigger" type="button" aria-expanded="false"><span>🎁 Gifts</span>${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="submenu-panel"><a href="shop.html">Gift Sets</a><a href="shop.html">Birthday Gifts</a><a href="shop.html">Return Gifts</a><a href="shop.html">Gift Boxes</a></div></div><div class="submenu-item"><button class="submenu-trigger" type="button" aria-expanded="false"><span>🏡 Lifestyle</span>${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="submenu-panel"><a href="shop.html">Drinkware</a><a href="shop.html">Home Decor</a><a href="shop.html">Desk Setup</a><a href="shop.html">Organizers</a></div></div><div class="submenu-item"><button class="submenu-trigger" type="button" aria-expanded="false"><span>👜 Accessories</span>${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="submenu-panel"><a href="shop.html">Tote Bags</a><a href="shop.html">Pouches</a><a href="shop.html">Keychains</a><a href="shop.html">Phone Accessories</a></div></div><a class="shop-single-link" href="shop.html">🧸 Plush &amp; Toys</a><a class="menu-banner compact-banner" href="shop.html"><img src="Assets/ChatGPT Image Jul 1, 2026 at 10_53_15 PM.png" alt="New stationery arrivals"><span><small>Cute things are here</small><strong>Discover New Arrivals</strong></span></a></div></div>`;
collectionLink.outerHTML=`<div class="nav-item has-dropdown collections-nav"><button class="nav-trigger" type="button" aria-expanded="false">Collections ${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="dropdown-panel collections-menu"><div class="mega-heading">Collections</div><a href="shop.html">Dream Collection <span>🌸</span></a><a href="shop.html">Bear Collection <span>🧸</span></a><a href="shop.html">Bunny Collection <span>🐰</span></a><a href="shop.html">Pastel Collection <span>🎀</span></a><a href="shop.html">Minimal Collection <span>🤍</span></a><a href="shop.html">Kawaii Collection <span>✨</span></a><a href="shop.html">Limited Edition <span>💖</span></a></div></div>`;
const generatedCollections=nav.querySelector('.collections-nav');
if(generatedCollections){generatedCollections.className='nav-item has-dropdown accessories-nav';generatedCollections.innerHTML=`<button class="nav-trigger" type="button" aria-expanded="false">Accessories ${svg('<path d="m8 10 4 4 4-4"/>')}</button><div class="dropdown-panel accessories-menu"></div>`}
[...nav.querySelectorAll('.shop-nav .submenu-item')].find(item=>item.querySelector('.submenu-trigger')?.textContent.includes('Accessories'))?.remove();
document.body.insertAdjacentHTML("beforeend",`<footer class="site-footer"><div class="footer-main"><div class="footer-container footer-grid"><div class="footer-brand"><a href="index.html"><img src="Assets/giraalogo.png" alt="Giraastore"></a><p>More than a store —<br>a lifestyle you’ll love.</p><div class="footer-socials"><a href="${instagram}" target="_blank" rel="noopener noreferrer" aria-label="Instagram">${svg('<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".5" fill="currentColor"/>')}</a><a href="#" aria-label="Facebook">${svg('<path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v5h4v-5h3l1-4h-4V9c0-.7.3-1 1-1Z"/>')}</a><a href="#" aria-label="Pinterest">${svg('<circle cx="12" cy="12" r="9"/><path d="M9.5 18 12 8.5c.5-1.8 3.5-1 2.8 1.5-.7 2.6-3.4 2.4-3.9.8-.8-2.4 1-4.5 3.2-4.5 3 0 4.6 2.2 4.1 4.8-.5 3-2.7 5.2-5.4 4.6"/>')}</a><a href="#" aria-label="YouTube">${svg('<rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 9 5 3-5 3Z"/>')}</a></div></div><nav class="footer-column"><h2>Shop</h2><a href="shop.html">All Products</a><a href="shop.html">New Arrivals</a><a href="shop.html">Best Sellers</a><a href="shop.html">Stationery</a><a href="shop.html">Accessories</a><a href="shop.html">Gifts</a><a href="shop.html">Lifestyle</a></nav><nav class="footer-column"><h2>Help &amp; Info</h2><a href="about.html">About Us</a><a href="contact.html">Contact Us</a><a href="faq.html">FAQ</a><a href="blog.html">Blog</a><a href="shipping-policy.html">Shipping Policy</a><a href="return-policy.html">Return &amp; Refund Policy</a><a href="terms.html">Terms &amp; Conditions</a><a href="privacy-policy.html">Privacy Policy</a></nav><div class="footer-column footer-contact"><h2>Customer Care</h2><a href="tel:+917039763941">+91 70397 63941</a><a href="mailto:support@giraastore.com">support@giraastore.com</a><p>Mon–Sat: 10AM–6PM<br>Sunday: Closed</p></div><div class="footer-payment"><h2>We Accept</h2><div class="payment-badges"><span><img src="Assets/visa.png" alt="Visa"></span><span><img src="Assets/master.png" alt="Mastercard"></span><span><img src="Assets/upi.png" alt="UPI"></span><span><img src="Assets/rupay.png" alt="RuPay"></span><span><img src="Assets/paypal.png" alt="PayPal"></span></div><h3>Secure &amp; Trusted</h3><div class="secure-note">${svg('<path d="M12 3 5 6v5c0 5 3 8.5 7 10 4-1.5 7-5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>')}<p>100% Secure Payments<br>and Protected Orders</p></div></div></div></div><div class="footer-bottom"><div class="footer-container"><p>© 2026 <span>Giraastore</span>. All Rights Reserved.</p><a class="back-to-top" href="#">↑</a></div></div></footer>`);
const menuButton=document.querySelector('.mobile-menu'),navigation=document.querySelector('.main-nav');
const helpFooterColumn=[...document.querySelectorAll('.site-footer .footer-column')].find(column=>column.querySelector('h2')?.textContent.trim()==='Help & Info');
helpFooterColumn?.querySelector('h2')?.insertAdjacentHTML('afterend','<a href="help-center.html">Help Center</a>');
helpFooterColumn?.insertAdjacentHTML('beforeend','<a href="disclaimer.html">Disclaimer</a>');
const catalogLinkRoutes={'new arrivals':'new-arrivals','best sellers':'best-sellers','sale':'sale','all products':'all','stationery':'stationery','notebooks':'notebooks','pens':'pens','stickers':'stickers','washi tape':'washi-tape','pencil cases':'pencil-cases','highlighters':'highlighters','gifts':'gifts','gift sets':'gift-sets','birthday gifts':'birthday-gifts','return gifts':'return-gifts','gift boxes':'gift-boxes','lifestyle':'lifestyle','drinkware':'drinkware','home decor':'home-decor','desk setup':'desk-setup','organizers':'organizers','accessories':'accessories','tote bags':'tote-bags','pouches':'pouches','keychains':'keychains','phone accessories':'phone-accessories','plush & toys':'toys','jewellery':'jewellery'};
document.querySelectorAll('a').forEach(link=>{const route=catalogLinkRoutes[link.textContent.trim().toLowerCase()];if(route)link.href=route==='all'?'shop.html':`shop.html?view=${route}`});
menuButton?.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.nav-item.has-dropdown').forEach(item=>item.querySelector('.nav-trigger')?.addEventListener('click',event=>{event.stopPropagation();const open=!item.classList.contains('open');document.querySelectorAll('.nav-item.has-dropdown').forEach(other=>other.classList.remove('open'));item.classList.toggle('open',open)}));
document.querySelectorAll('.submenu-trigger').forEach(trigger=>trigger.addEventListener('click',event=>{event.stopPropagation();trigger.closest('.submenu-item').classList.toggle('submenu-open')}));
document.addEventListener('click',event=>{if(!event.target.closest('.nav-item'))document.querySelectorAll('.nav-item.has-dropdown').forEach(item=>item.classList.remove('open'))});
document.querySelectorAll('.faq-question').forEach(btn=>btn.addEventListener('click',()=>{const open=btn.parentElement.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))}));
document.querySelectorAll('.wish').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('active');btn.textContent=btn.classList.contains('active')?'♥':'♡'}));
document.querySelector('.contact-form')?.addEventListener('submit',e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.textContent='Message sent ♡';b.disabled=true});
document.querySelector('.policy-menu')?.remove();
const heroCopy={
  "faq.html":["FAQ’s","Find answers to the most common questions about Giraastore."],
  "contact.html":["Contact Us","We’d love to hear from you! Reach out for any queries, feedback or support."],
  "return-policy.html":["Return & Exchange Policy","We want you to love what you ordered! If not, we’re here to help."],
  "shipping-policy.html":["Shipping Policy","All the information you need about shipping and delivery."],
  "terms.html":["Terms & Conditions","Please read these terms and conditions carefully before using our website."],
  "privacy-policy.html":["Privacy Policy","Your privacy is important to us. Learn how we collect, use and protect your information."]
};
if(heroCopy[currentFile]&&!document.body.matches('.faq-page,.contact-page')){
  const hero=document.querySelector(".page-hero");
  if(hero){hero.querySelector("h1").textContent=heroCopy[currentFile][0];hero.querySelector("p").textContent=heroCopy[currentFile][1]}
}
if(document.querySelector('.page-hero')&&!document.querySelector('.service-strip')){
  document.querySelector('main')?.insertAdjacentHTML('beforeend',`<section class="service-strip" aria-label="Store benefits"><article><span>♧</span><div><strong>Free Shipping</strong><small>Above ₹499</small></div></article><article><span>↻</span><div><strong>Easy Returns</strong><small>7-day return window</small></div></article><article><span>♢</span><div><strong>Secure Payments</strong><small>100% safe &amp; secure</small></div></article><article><span>♧</span><div><strong>Customer Support</strong><small>We’re always here to help</small></div></article></section>`);
}
